In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline
warnings.filterwarnings('ignore')
pd.set_option('display.maxcolumns',20)
pd.set_option('display.maxrows',25)

NameError: name 'warnings' is not defined

In [2]:
responses = pd.read_csv('../Niteo/Emergency_Response_Incidents.csv')

In [3]:
responses = responses.rename(columns={'Creation Date':'SDate','Closed Date':'EDate','Incident Type':'Incidents'})

In [4]:
responses['Borough']=responses.Borough.apply(lambda x:x.lower())

In [5]:
responses.sample(20)

,Incidents,Location,Borough,SDate,EDate,Latitude,Longitude
2180,Structural-Bricks,470 Park Avenue South,manhattan,7/9/2013 9:19:26 AM,7/9/2013 10:36:10AM,40.745456,-73.982540
1795,HazMat-High Carbon Monoxide,245 Grand Street,manhattan,1/4/2014 6:30:37 PM,1/4/2014 11:49:29PM,40.718293,-73.994322
2506,Fire-2nd Alarm,672 Decatur Street,brooklyn,1/11/2013 11:39:45 AM,1/11/2013 1:18:20PM,40.683450,-73.915908
1715,LawEnforcement-Suspicious Package,W 22 St & 5 Ave,manhattan,1/30/2014 12:35:08 PM,1/30/2014 12:51:29PM,40.740879,-73.990069
2255,Fire-Manhole,254 Park Ave South,manhattan,6/3/2013 1:26:39 PM,6/3/2013 4:52:01PM,40.738463,-73.987641
2343,LawEnforcement-Suspicious Package,JFK,queens,4/21/2013 4:27:11 PM,4/21/2013 5:22:38PM,40.648244,-73.788242
1274,Structural-Demolition,264 West Street,manhattan,8/30/2014 1:36:04 PM,8/31/2014 9:59:26AM,40.723076,-74.011574
532,Transportation-Commuter Bus,530 West 40 Street,manhattan,6/10/2015 10:04:47 AM,6/10/2015 2:16:07PM,40.759146,-73.998405
1427,Fire-10-76 (Commercial High Rise Fire),NaN,brooklyn,6/16/2014 3:37:07 PM,6/16/2014 5:07:17PM,NaN,NaN
2237,Fire-Collapse,5-18 50 Ave,queens,6/12/2013 2:49:05 PM,6/13/2013 1:41:13PM,40.743103,-73.956085
1987,Fire-Explosion,87-40 124th Street,queens,10/12/2013 1:31:27 AM,11/13/2013 2:35:00PM,40.699788,-73.826087
2141,Utility-Power Outage,84 Lamport Blvd,staten island,7/26/2013 12:54:55 PM,7/26/2013 5:54:06PM,40.596788,-74.078578
1078,HazMat-Other,840 Astor Ave,bronx,11/25/2014 8:14:47 AM,11/25/2014 9:14:33PM,40.859633,-73.862449
2442,Utility-Water Main,33 Franklin Avenue,brooklyn,2/24/2013 7:39:00 AM,2/24/2013 8:39:51AM,40.698068,-73.958725
1174,Law Enforcement-Suspicious Package,1115 Broadway,manhattan,10/21/2014 8:05:54 AM,10/21/2014 9:38:23AM,40.742916,-73.989185
615,Fire-Explosion,1436 Williamsbridge Road,bronx,5/8/2015 9:43:13 PM,5/8/2015 11:05:26PM,40.843055,-73.844885
2070,Fire-10-77 (Residential High Rise),335 Bowery,manhattan,9/3/2013 11:25:47 AM,9/3/2013 1:01:59PM,40.726044,-73.991908
225,Utility-Manhole,100 East 77th Street,manhattan,9/30/2015 6:59:41 AM,10/1/2015 8:19:11AM,40.774178,-73.961148
1408,Fire-Haz Mat,One New York Plaza,manhattan,6/23/2014 6:06:40 PM,6/23/2014 9:21:47PM,40.702592,-74.011671
2228,Transportation-Train Ground Level,Penn Station,manhattan,6/17/2013 6:07:42 PM,6/19/2013 8:26:55AM,NaN,NaN

In [6]:
responses.Incidents.describe()

count               2524
unique               284
top       Fire-2nd Alarm
freq                 203
Name: Incidents, dtype: object

In [8]:
responses.Location.describe()

count                     2295
unique                    2231
top       1 World Trade Center
freq                         5
Name: Location, dtype: object

In [122]:
test = responses.dropna()

In [17]:
test.sample(30)

,Incidents,Location,Borough,SDate,EDate,Latitude,Longitude
909,Transportation-Train Subway,Lexington Avenue & East 59 Street,manhattan,2/3/2015 10:06:46 AM,2/3/2015 11:56:27AM,40.762227,-73.968187
1301,HazMat-High Carbon Monoxide,East 83 Street & Chase Ct,brooklyn,8/13/2014 9:14:01 AM,8/13/2014 11:04:42AM,40.643158,-73.917951
539,Structural-Stability Problem,113-05 Jamaica Ave,queens,6/5/2015 4:11:50 PM,6/8/2015 4:52:58AM,40.697914,-73.835504
995,Fire-2nd Alarm,34 Rochester Avenue,brooklyn,1/5/2015 8:00:54 AM,1/5/2015 7:28:14PM,40.677974,-73.927484
425,Law Enforcement-Explosion,2016 La Fontaine Avenue,bronx,7/11/2015 11:49:18 AM,7/11/2015 12:58:26PM,40.847850,-73.893514
1793,HazMat-Fuel,Staten Island Expy & Richmond Avenue,staten island,1/5/2014 3:14:34 AM,1/5/2014 4:29:01AM,40.615031,-74.157373
431,Transportation-Train Ground Level,Rust Street & Maspeth Avenue,queens,7/8/2015 12:53:09 AM,7/8/2015 4:19:32PM,40.722899,-73.913848
1823,HazMat-High Carbon Monoxide,86th Street & 102 Avenue,queens,12/23/2013 11:23:09 PM,12/24/2013 8:08:13AM,40.681406,-73.853330
522,Fire-1st Alarm,420 Lexington Avenue,brooklyn,6/11/2015 9:36:50 PM,6/11/2015 11:02:48PM,40.688457,-73.944088
1426,Rescue-Other,West 33 Street & 7th Avenue,manhattan,6/17/2014 3:00:06 PM,6/17/2014 3:44:01PM,40.750318,-73.991111
1999,Fire-2nd Alarm,1092 Blake Avenue,brooklyn,10/4/2013 7:36:16 PM,10/4/2013 10:12:19PM,40.670348,-73.877738
2049,HazMat-High Carbon Monoxide,East 149 Street & Courtlandt Avenue,bronx,9/11/2013 4:09:53 PM,9/11/2013 6:02:30PM,40.816554,-73.919544
126,Fire-Brush,Kissam Avenue & Mill Road,staten island,11/13/2015 2:07:03 PM,11/13/2015 5:47:27PM,40.557282,-74.114170
1812,Fire-Explosion,Pelham Bay Park,bronx,12/30/2013 11:34:53 PM,12/31/2013 1:18:55AM,40.846650,-73.823931
436,Fire-2nd Alarm,103-28 105 Street,queens,7/7/2015 3:30:19 AM,7/7/2015 5:38:56AM,40.683522,-73.836711
2340,Structural-Partial Collapse,31-19 30th Avenue,queens,4/22/2013 12:08:43 PM,4/23/2013 10:54:49AM,40.766799,-73.921160
38,Structural-Other,146 Wilson Street,brooklyn,12/14/2015 9:26:47 AM,12/18/2015 11:21:19AM,40.705792,-73.961794
1259,Structural-Evacuation,1228 Union Avenue,bronx,9/12/2014 11:28:09 AM,9/12/2014 1:35:16PM,40.829455,-73.899058
1922,Structural-Sidewalk Shed,255 East 88th Street,manhattan,11/16/2013 8:46:20 PM,12/17/2013 6:25:04PM,40.779620,-73.951814
1768,Fire-3rd Alarm,2390 Hoffman Street,bronx,1/9/2014 3:54:41 PM,1/11/2014 12:09:08PM,40.855635,-73.888777
2387,LawEnforcement-Suspicious Package,East 40 Street & 3rd Avenue,manhattan,3/29/2013 9:50:46 AM,3/29/2013 10:16:29AM,40.749484,-73.975382
2160,Transportation-Delay in Commuter Service,West 34th Street & 8th Avenue- NY Penn Station,manhattan,7/17/2013 5:54:22 PM,7/17/2013 10:54:15PM,40.752190,-73.993464
1593,Structural-Stability Problem,11 Sumpter St,brooklyn,3/30/2014 5:06:54 PM,3/31/2014 7:51:21PM,40.679228,-73.926520
153,Structural-Confined Space,109 East 42 Street,manhattan,11/1/2015 4:05:08 AM,11/1/2015 5:01:35AM,40.714430,-74.006099
378,Fire-2nd Alarm,1213 Avenue Z,brooklyn,7/25/2015 9:24:21 PM,7/26/2015 10:22:42PM,40.587653,-73.957289
2490,HazMat-High Carbon Monoxide,631 9th Ave.,manhattan,1/25/2013 4:09:39 PM,1/25/2013 6:12:02PM,40.760046,-73.991467
142,Aviation-Other,Beach 219 Street & Breezy Point Boulevard,queens,11/4/2015 8:13:16 PM,11/5/2015 9:33:24PM,40.554941,-73.927002
2065,Structural-Scaffold,East 42 Street & 1 Avenue,manhattan,9/5/2013 2:55:37 PM,9/5/2013 4:45:17PM,40.748800,-73.969846
2416,LawEnforcement-Suspicious Package,40 Wall Street,manhattan,3/15/2013 9:36:02 AM,3/15/2013 10:46:05AM,40.706625,-74.009875
2315,Structural-Car VS Building,15 Tanglewood Dr,staten island,5/6/2013 1:11:34 PM,5/6/2013 3:13:55PM,40.567081,-74.151760

In [125]:
def sepInc(x):
    x = x.split('-')
    return x[0]
test['Incidents'] = test.Incidents.apply(sepInc)

In [126]:
test.head()

,Incidents,Location,Borough,SDate,EDate,Latitude,Longitude
1,Transportation,Marcy Ave & Broadway,brooklyn,12/31/2015 5:00:43 PM,1/2/2016 4:03:10AM,40.708426,-73.957904
2,Law Enforcement,435 Ocean Parkway,brooklyn,12/30/2015 1:55:21 PM,12/30/2015 2:00:18PM,40.637832,-73.973045
4,Fire,347 East 84 Street,manhattan,12/28/2015 6:52:05 PM,12/28/2015 8:40:08PM,40.776093,-73.951568
5,Fire,30 Richardson Street,brooklyn,12/28/2015 1:46:20 AM,Active,40.718195,-73.951083
6,Fire,119-19 146 St,queens,12/27/2015 4:47:41 PM,12/27/2015 7:18:23PM,40.678287,-73.793753

In [127]:
test = test.replace(['LawEnforcment'],['Law Enforcement'])

In [128]:
pd.crosstab(test['Incidents'],test.Borough)

Borough          bronx  brooklyn  citywide  manhattan  queens  staten island
Incidents
Administration       2         6         1         10       5              0
Aviation             0         0         0          1       2              1
Fire               112       171         0        209     118             42
HazMat              21        46         0         54      42              6
Law Enforcement     10        31         0         74      29             10
LawEnforcement      12        36         0         76      19             11
Marine               0         3         0          3       0              1
Medical              4        10         0          7       5              1
Other                1         2         0          3       1              1
Rescue               7        11         0         40       9              3
Structural          45       103         0        143      49             16
Transportation       1        17         0         39      11              2
Utility             76       105         0        170      72             26
Weather              0         1         0          0       2              1

In [20]:
test = test.loc[0::,['Incidents','Location']]

In [22]:
test.head()

                            Incidents              Location
1         Transportation-Train Subway  Marcy Ave & Broadway
2  Law Enforcement-Suspicious Package     435 Ocean Parkway
4                      Fire-2nd Alarm    347 East 84 Street
5                      Fire-5th Alarm  30 Richardson Street
6                      Fire-2nd Alarm         119-19 146 St

In [130]:
def parseSt(x):
    if '&' in x:
        return x
    else:
        x = x.split(' ')
        if len(x)==3:
            return x[1]
        elif len(x) == 4:
            y = x[1]+x[2]
            return y
test['Street'] = test.Location.apply(parseSt)

In [54]:
test.head()

,Incidents,Location,Street,Details
1,Transportation-Train Subway,Marcy Ave & Broadway,Marcy Ave & Broadway,Train Subway
2,Law Enforcement-Suspicious Package,435 Ocean Parkway,Ocean,Suspicious Package
4,Fire-2nd Alarm,347 East 84 Street,East84,2nd Alarm
5,Fire-5th Alarm,30 Richardson Street,Richardson,5th Alarm
6,Fire-2nd Alarm,119-19 146 St,146,2nd Alarm

In [129]:
pd.crosstab(test['Details'],test.Street)

KeyError: 'Details'

In [55]:
test.Street.describe()

count     2051
unique    1398
top       Park
freq        19
Name: Street, dtype: object

In [56]:
test.Street.count()

2051

In [131]:
def cleanInc(x):
    x=x.split('-')
    return x[1]
test['Details'] = test.Incidents.apply(cleanInc)

IndexError: list index out of range

In [58]:
test.head()

,Incidents,Location,Street,Details
1,Transportation-Train Subway,Marcy Ave & Broadway,Marcy Ave & Broadway,Train Subway
2,Law Enforcement-Suspicious Package,435 Ocean Parkway,Ocean,Suspicious Package
4,Fire-2nd Alarm,347 East 84 Street,East84,2nd Alarm
5,Fire-5th Alarm,30 Richardson Street,Richardson,5th Alarm
6,Fire-2nd Alarm,119-19 146 St,146,2nd Alarm

In [59]:
testSt = test.loc[0::,['Street','Details']]

In [60]:
testSt.head()

                 Street             Details
1  Marcy Ave & Broadway        Train Subway
2                 Ocean  Suspicious Package
4                East84           2nd Alarm
5            Richardson           5th Alarm
6                   146           2nd Alarm

In [61]:
grpSt = testSt.groupby(['Street'])

In [62]:
grpSt.describe()

                                                          Details
Street
                                   count                        2
                                   unique                       2
                                   top             Injured Worker
                                   freq                         1
 3rd Ave & East 117 St.            count                        1
                                   unique                       1
                                   top             Broken Hydrant
                                   freq                         1
1                                  count                        6
                                   unique                       5
                                   top                  1st Alarm
                                   freq                         2
1 Ave &  66 St                     count                        1
                                   unique                       1
                                   top                  1st Alarm
                                   freq                         1
10                                 count                        1
                                   unique                       1
                                   top                    Haz Mat
                                   freq                         1
101                                count                        1
                                   unique                       1
                                   top                   Chemical
                                   freq                         1
101 Street & Fort Hamilton Parkway count                        1
                                   unique                       1
                                   top           Gas Main Rupture
                                   freq                         1
103                                count                        1
                                   unique                       1
...                                                           ...
thompson street & Front Street     top           Gas Main Rupture
                                   freq                         1
vyse                               count                        1
                                   unique                       1
                                   top     Life Safety Violations
                                   freq                         1
w 28 street & Neptune Ave          count                        1
                                   unique                       1
                                   top               Power Outage
                                   freq                         1
w35                                count                        1
                                   unique                       1
                                   top                         10
                                   freq                         1
west143                            count                        1
                                   unique                       1
                                   top       High Carbon Monoxide
                                   freq                         1
west34                             count                        1
                                   unique                       1
                                   top                         10
                                   freq                         1
west57                             count                        1
                                   unique                       1
                                   top                      Other
                                   freq                         1
west91                             count                        1
                                   unique                       1
                                   top                      Solid
                                   freq                         1

[5592 rows x 1 columns]

In [63]:
grpSt.count()

                                    Details
Street
                                          2
 3rd Ave & East 117 St.                   1
1                                         6
1 Ave &  66 St                            1
10                                        1
101                                       1
101 Street & Fort Hamilton Parkway        1
103                                       1
103rd Street & Roosevelt Avenue           1
104                                       1
105                                       1
108                                       1
110                                       1
110th                                     1
111                                       3
111th                                     1
112th                                     1
113th                                     1
116                                       1
11th                                      1
12                                        3
12 Avenue & 78 Street                     1
12 Avenue & West 46 Street                1
12 Avenue & West 47 Street                1
120th                                     1
121                                       1
121 St & Atlantic Avenue                  1
124th                                     1
125                                       1
126                                       1
...                                     ...
avenue H & New York Avenue                1
beach113                                  1
bedford                                   1
belmont                                   1
bleecker                                  1
burton                                    1
columbus                                  1
e117th                                    1
e12                                       1
east120                                   1
east72                                    1
grand                                     1
jay                                       2
jennings street & charlotte street        1
jerome                                    1
keating                                   1
livingston street & smith street          1
lloyd                                     1
marcusgarvey                              1
montauk                                   1
roosevelt                                 1
stockholm                                 1
thompson street & Front Street            1
vyse                                      1
w 28 street & Neptune Ave                 1
w35                                       1
west143                                   1
west34                                    1
west57                                    1
west91                                    1

[1398 rows x 1 columns]

In [64]:
grpCnt = grpSt.count()

In [65]:
grpCnt

                                    Details
Street
                                          2
 3rd Ave & East 117 St.                   1
1                                         6
1 Ave &  66 St                            1
10                                        1
101                                       1
101 Street & Fort Hamilton Parkway        1
103                                       1
103rd Street & Roosevelt Avenue           1
104                                       1
105                                       1
108                                       1
110                                       1
110th                                     1
111                                       3
111th                                     1
112th                                     1
113th                                     1
116                                       1
11th                                      1
12                                        3
12 Avenue & 78 Street                     1
12 Avenue & West 46 Street                1
12 Avenue & West 47 Street                1
120th                                     1
121                                       1
121 St & Atlantic Avenue                  1
124th                                     1
125                                       1
126                                       1
...                                     ...
avenue H & New York Avenue                1
beach113                                  1
bedford                                   1
belmont                                   1
bleecker                                  1
burton                                    1
columbus                                  1
e117th                                    1
e12                                       1
east120                                   1
east72                                    1
grand                                     1
jay                                       2
jennings street & charlotte street        1
jerome                                    1
keating                                   1
livingston street & smith street          1
lloyd                                     1
marcusgarvey                              1
montauk                                   1
roosevelt                                 1
stockholm                                 1
thompson street & Front Street            1
vyse                                      1
w 28 street & Neptune Ave                 1
w35                                       1
west143                                   1
west34                                    1
west57                                    1
west91                                    1

[1398 rows x 1 columns]

In [75]:
testCnt = grpCnt[grpCnt.Details>18]

In [76]:
testCnt

        Details
Street
Park         19

In [72]:
testCnt.describe()

          Details
count  127.000000
mean     4.669291
std      2.639911
min      3.000000
25%      3.000000
50%      4.000000
75%      5.000000
max     19.000000

In [77]:
test.head()

,Incidents,Location,Street,Details
1,Transportation-Train Subway,Marcy Ave & Broadway,Marcy Ave & Broadway,Train Subway
2,Law Enforcement-Suspicious Package,435 Ocean Parkway,Ocean,Suspicious Package
4,Fire-2nd Alarm,347 East 84 Street,East84,2nd Alarm
5,Fire-5th Alarm,30 Richardson Street,Richardson,5th Alarm
6,Fire-2nd Alarm,119-19 146 St,146,2nd Alarm

In [79]:
testDet = test[test.Street=='Park']

In [80]:
testDet

,Incidents,Location,Street,Details
164,HazMat-Other,737 Park Avenue,Park,Other
211,Utility-Water Main,695 Park Avenue,Park,Water Main
299,HazMat-Other,695 Park Avenue,Park,Other
796,Utility-Power Outage,3080 Park Avenue,Park,Power Outage
975,HazMat-Liquid,250 Park Avenue,Park,Liquid
1365,Fire-Other,1581 Park Avenue,Park,Other
1407,Utility-Other,355 Park Place,Park,Other
1511,Fire-10-76 (Commercial High Rise),643 Park Avenue,Park,10
1630,Fire-Collapse,1646 Park Ave,Park,Collapse
1729,Structural-Life Safety Violations,4461 Park Avenue,Park,Life Safety Violations
1769,Structural-Scaffold,1150 Park Ave,Park,Scaffold
1802,Fire-10-76 (Commercial High Rise),200 Park Avenue,Park,10
1881,Rescue-Confined Space,331 Park Ave,Park,Confined Space
1989,Utility-Gas High Pressure,1785 Park Place,Park,Gas High Pressure
1998,Fire-High Angle Rescue,3 Park Avenue,Park,High Angle Rescue
2037,Rescue-High Angle,3 Park Avenue,Park,High Angle
2143,Structural-Sidewalk Collapse,3204 Park Ave,Park,Sidewalk Collapse
2219,Structural-Scaffold,1165 Park Ave,Park,Scaffold
2352,LawEnforcement-Suspicious Package,390 Park Ave.,Park,Suspicious Package

In [82]:
testDet.Details.count()

19

In [84]:
test.head()

,Incidents,Location,Street,Details
1,Transportation-Train Subway,Marcy Ave & Broadway,Marcy Ave & Broadway,Train Subway
2,Law Enforcement-Suspicious Package,435 Ocean Parkway,Ocean,Suspicious Package
4,Fire-2nd Alarm,347 East 84 Street,East84,2nd Alarm
5,Fire-5th Alarm,30 Richardson Street,Richardson,5th Alarm
6,Fire-2nd Alarm,119-19 146 St,146,2nd Alarm

In [85]:
def sepInc(x):
    x = x.split('-')
    return x[0]
test['Incidents'] = test.Incidents.apply(sepInc)

In [86]:
test.head()

,Incidents,Location,Street,Details
1,Transportation,Marcy Ave & Broadway,Marcy Ave & Broadway,Train Subway
2,Law Enforcement,435 Ocean Parkway,Ocean,Suspicious Package
4,Fire,347 East 84 Street,East84,2nd Alarm
5,Fire,30 Richardson Street,Richardson,5th Alarm
6,Fire,119-19 146 St,146,2nd Alarm

In [108]:
pd.crosstab(test['Incidents'],test.Street)

Street,,3rd Ave & East 117 St.,1,1 Ave & 66 St,10,101,101 Street & Fort Hamilton Parkway,103,103rd Street & Roosevelt Avenue,104,...,roosevelt,stockholm,thompson street & Front Street,vyse,w 28 street & Neptune Ave,w35,west143,west34,west57,west91
Incidents,,,,,,,,,,,,,,,,,,,,,
Administration,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Aviation,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Fire,0,0,2,1,0,0,0,0,1,0,...,1,1,0,0,0,1,0,1,0,0
HazMat,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
Law Enforcement,0,0,1,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
LawEnforcement,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Marine,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Medical,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Other,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Rescue,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Structural,0,0,1,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
Transportation,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Utility,1,1,0,0,0,0,1,0,0,0,...,0,0,1,0,1,0,0,0,0,0
Weather,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [87]:
testDet = test[test.Street=='Park']

In [88]:
testDet

           Incidents          Location Street                 Details
164           HazMat   737 Park Avenue   Park                   Other
211          Utility   695 Park Avenue   Park              Water Main
299           HazMat   695 Park Avenue   Park                   Other
796          Utility  3080 Park Avenue   Park            Power Outage
975           HazMat   250 Park Avenue   Park                  Liquid
1365            Fire  1581 Park Avenue   Park                   Other
1407         Utility    355 Park Place   Park                   Other
1511            Fire   643 Park Avenue   Park                      10
1630            Fire     1646 Park Ave   Park                Collapse
1729      Structural  4461 Park Avenue   Park  Life Safety Violations
1769      Structural    1150  Park Ave   Park                Scaffold
1802            Fire  200  Park Avenue   Park                      10
1881          Rescue      331 Park Ave   Park          Confined Space
1989         Utility   1785 Park Place   Park       Gas High Pressure
1998            Fire     3 Park Avenue   Park       High Angle Rescue
2037          Rescue     3 Park Avenue   Park              High Angle
2143      Structural     3204 Park Ave   Park       Sidewalk Collapse
2219      Structural     1165 Park Ave   Park                Scaffold
2352  LawEnforcement     390 Park Ave.   Park      Suspicious Package

In [105]:
testDet.Incidents.describe()

count       19
unique       6
top       Fire
freq         5
Name: Incidents, dtype: object

In [97]:
testDet = testDet.loc[0::,['Incidents','Street']]

In [106]:
ParkFire = testDet.groupby('Incidents')

ParkFire.describe()

In [107]:
ParkFire.describe()

                      Street
Incidents
Fire           count       5
               unique      1
               top      Park
               freq        5
HazMat         count       3
               unique      1
               top      Park
               freq        3
LawEnforcement count       1
               unique      1
               top      Park
               freq        1
Rescue         count       2
               unique      1
               top      Park
               freq        2
Structural     count       4
               unique      1
               top      Park
               freq        4
Utility        count       4
               unique      1
               top      Park
               freq        4